### ISSUE TITLE
Erroneous error message when trying to update using setEmployeeDataUploadUtility

### ISSUE THREAD

**Issue by CTO4556** [TheAlphaSchoolSystemPTYLTD/data-upload-utility#14]
HI there,

Anyone know what this means in term of the errorcode and why it is being thrown?

"Element TCH_CODE is undefined in STREMPLOYEE."

We are trying to maintain a staff record but this is coming back as the error via the return.

We cannot find a reference to this error anywhere to assist.

Thanks

Chris

**Comment by bradftass** [comment]
Hi Chris,

Thank you for raising this issue.  It appears to be a longstanding bug that has gone unreported.  We will need to make a program change that we can deliver in our May release, if not before.

At this stage, the "school_email" field that you are trying to update will only work if the employee is not a teacher.  If they are a teacher, it will return an error message as per the documentation:

 __invalid: {
 	"school_email": "'school_email' is allowed for Non Teachers only"
 }

I would suggest omitting the "school_email" field until this fix is deployed and you can continue to use the API.  The "e_mail" field may be able to serve your needs for the time being?

I will respond here when the bug has been deployed to the customer base.

Regards,
Brad Fleming
Software Development Manager

**Comment by CTO4556** [comment]
Thanks Brad,

That error is throwing on multiple fields, not just school_email. Is that correct and is that what you are looking to fix?

We are using School_email to create the initial record via the hr api, which would work as there’s no teacher.

When we create a teacher record outside of the API, I understand that record becomes unavailable to then update.

I would question the logic for this though, and ask you to review it, as we would like to update school_email outside of the personal email ‘email’ field ongoing if that makes sense?

Also - if you could include termination date it would be ver helpful from an HR perspective.

Thanks

Chris


￼

**Comment by bradftass** [comment]
Thanks Chris,

Do you have any details on other fields that are throwing an error?  If any packets contain the "school_email" field it will throw the error you mentioned above.

I agree the UI not allowing "syncing" of the Teacher email and the School email on the Employee program is frustrating as you can only update that field in the Teacher Maintenance program.  This is getting raised in our next software planning meeting to try and get it resolved sooner.  It has a number of programs that interact with those fields so the impact may be a bit higher.

The termination date is a little more complex as the Reason for termination is required when you enter this value in the UI.  We would need to create an additional endpoint so API users would know the valid values to use with the Reason field.
I will raise this with subject matter experts and our API coordinator to see if there is scope for this work in the near future.

I hope that helps, 
Brad

**Comment by CTO4556** [comment]
Thanks Brad,

The School_email is a critical field to be able to updated at our end (whether it’s a teacher or not), as we utilise this field for Automations for username/AD account creation. We cannot use email as that’s their personal email.

To give an overview of the context:

When are interacting with TASS from our HR product, we are doing the following:

Creation of a person using EmployeeHR with basic ‘person details’ to create a record in TASS.
This then creates AD with email/username etc
This then interacts with external LOB Applications.

Error trapping occurs when the following happens:

The school email address has already been used previously requiring it to be updated. In the instance that a teacher record has already been created, then we have no way of programmatically updating this field via the uploader.
The person gets married and is a Teacher - we again have no way of updating this field.

We can pretty much work around any other limitations on what we can write to, but the school_email is a critical dependency.

See what you can do - Logically I cannot understand why it wouldn’t allow a write in terms of functionality within the TASS Web App - is there a reason that I am unaware of?

Thanks for coming back to me,

Chris 



￼

**Comment by bradftass** [comment]
Hi Chris,

Thanks for the context, that makes it much clearer in why this needs to be resolved.  I will relay this to the team to get it progressed.

As for the reason why the UI doesn't allow it to update in the Employee screen when they are a Teacher.  I unfortunately don't know.  I don't see why the two email fields between teacher an employee school email can't be linked (or synced).  Once I hear back about this, I will let you know.

Thanks,
Brad

**Comment by CTO4556** [comment]
Thanks Brad,Is there a way of updating their school email address if they are a teacher?ChrisOn 24 Mar 2023, at 3:40 pm, Brad Fleming ***@***.***> wrote:﻿
Hi Chris,
Thanks for the context, that makes it much clearer in why this needs to be resolved.  I will relay this to the team to get it progressed.
As for the reason why the UI doesn't allow it to update in the Employee screen when they are a Teacher.  I unfortunately don't know.  I don't see why the two email fields between teacher an employee school email can't be linked (or synced).  Once I hear back about this, I will let you know.
Thanks,
Brad

**Comment by bradftass** [comment]
Hi Chris,

You can update it using the IdM API:
https://github.com/TheAlphaSchoolSystemPTYLTD/IdM/blob/master/SetEmployee.md

If you include the "school_email" it will update the employee school_email as well as the teacher email so they will be in sync.
This further highlights the inconsistency that I will be discussing internally next week.

Thanks,
Brad

**Comment by CTO4556** [comment]
Ohh - I feel we are making progress on this.For us automation is a huge part of the strategy and it’s essential to maintain a single source of truth in TASS, whatever associated system is being used to maintain those records.Thanks for the information - we are inching in the right direction.Have a wonderful weekend,Chris On 24 Mar 2023, at 4:25 pm, Brad Fleming ***@***.***> wrote:﻿
Hi Chris,
You can update it using the IdM API:
https://github.com/TheAlphaSchoolSystemPTYLTD/IdM/blob/master/SetEmployee.md
If you include the "school_email" it will update the employee school_email as well as the teacher email so they will be in sync.
This further highlights the inconsistency that I will be discussing internally next week.
Thanks,
Brad

**Comment by CTO4556** [comment]
Can I just clarify that we can use that routine to update the school_email by passing the employee code and school_email parameters and that’s all - ie not setup a Tassweb specific user and it doesn’t rely on it being a teacher or non-teacher?ChrisOn 24 Mar 2023, at 6:02 pm, Chris Topp ***@***.***> wrote:﻿Ohh - I feel we are making progress on this.For us automation is a huge part of the strategy and it’s essential to maintain a single source of truth in TASS, whatever associated system is being used to maintain those records.Thanks for the information - we are inching in the right direction.Have a wonderful weekend,Chris On 24 Mar 2023, at 4:25 pm, Brad Fleming ***@***.***> wrote:﻿
Hi Chris,
You can update it using the IdM API:
https://github.com/TheAlphaSchoolSystemPTYLTD/IdM/blob/master/SetEmployee.md
If you include the "school_email" it will update the employee school_email as well as the teacher email so they will be in sync.
This further highlights the inconsistency that I will be discussing internally next week.
Thanks,
Brad

**Comment by bradftass** [comment]
Hi Chris,

That's correct, you should only need to pass in the 'user_code' (Employee code) and the 'school_email' fields to make the change.

**Comment by tassweb-talon** [comment]
issue fixed in v58.5, ticket closed.
