### ISSUE TITLE
setEmployeeDataUploadUtility.md does not have an option to Termination Date

### ISSUE THREAD

**Issue by CTO4556** [TheAlphaSchoolSystemPTYLTD/data-upload-utility#19]
Hi there,

Can you add Termination Date into the uploader as we need to off board employees when they leave from our HR product. Currently we have to enter this in twice.

We can put start_date in, but not end_date.

Chris

**Comment by scottetass** [comment]
Hi,

Although the documentation does not indicate it, you can now update the term_date and cessation_type fields in the setEmployeeDataUploadUtility endpoint.

![image](https://github.com/user-attachments/assets/41c68174-9c34-41e0-aff2-b564a8d38ec4)

![image](https://github.com/user-attachments/assets/9b446649-b9b1-4c7d-8125-83327f8e7014)

I will update the documentation to reflect this ability.

Thanks, Scott

**Comment by CTO4556** [comment]
Hi Scott,

Is this live now? Or is it in a future release?

Chris

**Comment by scottetass** [comment]
Hi Chris,

It should be possible right now to pass in parameters term_date and cessation_type and have their values update in the database.

Thanks, Scott

**Comment by CTO4556** [comment]
Thanks Scott!

Chris
